-- 코드를 입력하세요
SELECT F1.PRODUCT_ID, PRODUCT_NAME, AMOUNT * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT F1 JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
                       FROM FOOD_ORDER
                       WHERE PRODUCE_DATE LIKE '2022-05%'
                       GROUP BY PRODUCT_ID) F2
    ON F1.PRODUCT_ID = F2.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
    