-- 코드를 입력하세요
SELECT A1.ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS A1 JOIN (SELECT ANIMAL_ID
                      FROM ANIMAL_INS
                      WHERE SEX_UPON_INTAKE LIKE 'Intact%') A2
    ON A1.ANIMAL_ID = A2.ANIMAL_ID
WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY ANIMAL_ID;