-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R1 
    JOIN (SELECT MEMBER_ID
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC
            LIMIT 1) R2
        ON R1.MEMBER_ID = R2.MEMBER_ID
    LEFT JOIN MEMBER_PROFILE
        ON R1.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;