-- 코드를 입력하세요
WITH RECURSIVE TIME
AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
)

SELECT TIME.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIME LEFT OUTER JOIN (SELECT *, HOUR(DATETIME) AS HOUR
               FROM ANIMAL_OUTS) T2
    ON TIME.HOUR = T2.HOUR
GROUP BY 1
ORDER BY 1;