-- 코드를 입력하세요
# SELECT *
# FROM ANIMAL_INS A1 JOIN ANIMAL_OUTS A2
#     ON A1.ANIMAL_ID = A2.ANIMAL_ID;
    
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_INS.ANIMAL_ID
                       FROM ANIMAL_INS JOIN ANIMAL_OUTS
                            ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID)
ORDER BY DATETIME
LIMIT 3;