-- 코드를 입력하세요
# SELECT PT_NO, MCDP_CD, APNT_CNCL_YN, MDDR_ID, APNT_YMD
# FROM APPOINTMENT
# WHERE MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N';

SELECT APNT_NO, P.PT_NAME, A.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A 
    JOIN PATIENT P
        ON A.PT_NO = P.PT_NO
    JOIN DOCTOR D
        ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = 'CS' AND APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;