-- 코드를 작성해주세요
SELECT H1.DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM HR_DEPARTMENT H1 JOIN (SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
                        FROM HR_EMPLOYEES
                        GROUP BY DEPT_ID) H2
    ON H1.DEPT_ID = H2.DEPT_ID
ORDER BY AVG_SAL DESC;