-- 코드를 작성해주세요
# SELECT ID, FISH_TYPE, MAX(LENGTH)
# FROM FISH_INFO
# GROUP BY FISH_TYPE;

SELECT ID, FISH_NAME_INFO.FISH_NAME, FISH_INFO2.LENGTH
FROM FISH_INFO 
    JOIN FISH_NAME_INFO
        ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
         FROM FISH_INFO
         GROUP BY FISH_TYPE) FISH_INFO2
        ON FISH_INFO.FISH_TYPE = FISH_INFO2.FISH_TYPE AND FISH_INFO.LENGTH = FISH_INFO2.LENGTH;
