-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_OUTS.ANIMAL_ID
                       FROM ANIMAL_OUTS JOIN ANIMAL_INS
                            ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID)
ORDER BY ANIMAL_ID;